### ISSUE TITLE
Can't install in portable Project.

### ISSUE THREAD

**Issue by joanvq** [AlejandroRuiz/PayPal.Forms#13]
I could not install the plugin into my portable projects. iOS and Android were OK but in portable I had to install it manually adding dll of the package. 
As a suggestion I would add the way to install the Portable plugin with dll's into the project.

**Comment by AlejandroRuiz** [comment]
Please check the example apps inside this repo it work for profile 78

**Comment by jamesatgithub** [comment]
it's better to mention the specific profile in the readme

**Comment by jamesatgithub** [comment]
@AlejandroRuiz is there any reason that this Forms plugin is based on Profile78 instead of Profile111 which is the default profile when you create a Xamarin.Forms PCL project? It took me some hours to uninstall all nuget packages from my existing project then re-install and fixed other references issues like Profile111 included HttpClient while Profile78 not and had to install HttpClient nuget.

**Comment by AlejandroRuiz** [comment]
111 is the default for Windows on VS and 78 for Xamarin Studio on Mac im using the default one for my Mac system probably in the future will be available for other PCL profiles / .Net frameworks
