### ISSUE TITLE
issue while installing .NETPortable,Version=v4.5, 

### ISSUE THREAD

**Issue by shamnu** [AlejandroRuiz/PayPal.Forms#34]
Could not install package 'PayPal.Forms 2.16.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by DerColonel** [comment]
I am having the same issuse when trying to add PayPal.Forms to our PCL project. The NuGet package targets "portable-net45+win8+wpa81+wp8":
https://github.com/AlejandroRuiz/PayPal.Forms/blob/c5dba51833fbd3a5a2a085df32aa64e6a3a58744/MobileApps/PayPal.Forms.nuspec#L33
which is Profile259 (https://docs.microsoft.com/en-us/nuget/schema/target-frameworks).

Our project targets Profile111 (portable-net45+win8+wpa81) and when trying to install PayPal.Forms we get that error.
However, even if we change the TargetFrameworkProfile in our .csproj to "Profile259" we still get that error. I would be grateful for any information on this issue.

**Comment by AlejandroRuiz** [comment]
Now the plug-in only supports "Profile78"

**Comment by DerColonel** [comment]
Thanks for the quick reply.

@shamnu maybe this will help:
I worked around this by adding the dependency directly to the Android project instead of the PCL project. Then, I used DependencyService to implement payments in the Android project and call them via their Interface in the PCL project. I haven't added it to our iOS project yet but it should work similarly. The obvious downside is duplicate code in the Android and iOS projects, but at least it seems to work as far as I can tell right now.

@AlejandroRuiz Do you see any other downside in using the workaround mentioned above?

**Comment by shamnu** [comment]
@DerColonel @AlejandroRuiz thanks for the support.  i done a work around, adding the dll from Android project to PCL and it works for me

**Comment by AlejandroRuiz** [comment]
The project will be updated to net standards once Visual Studio Mac support it in a 100% so meanwhile the project will keep using profile 78

**Comment by AlejandroRuiz** [comment]
Good news guys profile 259 and netstandards1.x are now supported, you can update to 2.17.1 right now
